[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

[fuzz]
runs = 1000
max_test_rejects = 400
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
